spring:
   application:
     name: EmployeeClient
server:
  port: 8004  
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
      preferIpAddress: true 

